---
- name: Create VS
  hosts: bigip
  gather_facts: false
  connection: local
    
  vars:
    virtual_addr: "{{ virtual_ip }}"
    uri_method: "POST"

  tasks:
  - set_fact:
     tenant_body: "{{ lookup('file', '../app-templates/{{ f5_template }}.json', split_lines=False) }}"
  
  - debug:
      msg: "virtual_addr = {{ virtual_addr }} and virtual_ip = {{ virtual_ip }} and tenant_body = {{tenant_body}}"
 
      
    ##### AS3 POST ##### 
  - name: URI POST Tenant
    uri:
       url: "https://{{ inventory_hostname }}/mgmt/shared/appsvcs/declare"
       method: "{{ uri_method }}"
       user: "admin"
       password: "admin"
       validate_certs: no
       body: "{{ lookup('template', '../j2/tenant_base.j2') }}"
       body_format: json
