---
- name: Create VS
  hosts: bigip
  gather_facts: false
  connection: local
    
  vars:
    uri_method: "POST"

  tasks:
  
  - set_fact:
     tenant_body: "{{ lookup('file', '../app-templates/{{ f5_template }}.json', split_lines=False) }}"
   
    ### AS3 POST ###
  - name: URI POST Tenant
    uri:
       url: "https://{{ inventory_hostname }}/mgmt/shared/appsvcs/declare"
       method: "{{ uri_method }}"
       user: "{{ lookup('env', 'ANSIBLE_NET_USERNAME') }}"
       password: "{{ lookup('env', 'ANSIBLE_NET_PASSWORD') }}"
       validate_certs: no
       body: "{{ lookup('template', '../j2/tenant_base.j2') }}"
       body_format: json
